[build]
command = "g++ -std=c++17 src/server.cpp src/blockchain/*.cpp src/crypto/*.cpp src/block/*.cpp src/transaction/*.cpp src/wallet/*.cpp -Iinclude -lssl -lcrypto -o server"

[start]
command = "./server"
